In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/basketball/nba.sqlite
/kaggle/input/basketball/csv/other_stats.csv
/kaggle/input/basketball/csv/draft_history.csv
/kaggle/input/basketball/csv/team_details.csv
/kaggle/input/basketball/csv/player.csv
/kaggle/input/basketball/csv/draft_combine_stats.csv
/kaggle/input/basketball/csv/team_info_common.csv
/kaggle/input/basketball/csv/common_player_info.csv
/kaggle/input/basketball/csv/team_history.csv
/kaggle/input/basketball/csv/game.csv
/kaggle/input/basketball/csv/game_summary.csv
/kaggle/input/basketball/csv/officials.csv
/kaggle/input/basketball/csv/game_info.csv
/kaggle/input/basketball/csv/line_score.csv
/kaggle/input/basketball/csv/play_by_play.csv
/kaggle/input/basketball/csv/team.csv
/kaggle/input/basketball/csv/inactive_players.csv

In [2]:
import sqlite3 as sql
print ('Sqlite is ready')

Sqlite is ready

In [3]:
path="/kaggle/input/basketball/nba.sqlite"
conn= sql.connect(path)
print ("Database is connected")

Database is connected

In [4]:
t1=pd.read_sql_query("Select * FROM player",conn)
print(t1)

           id            full_name first_name     last_name  is_active
0       76001       Alaa Abdelnaby       Alaa     Abdelnaby          0
1       76002      Zaid Abdul-Aziz       Zaid    Abdul-Aziz          0
2       76003  Kareem Abdul-Jabbar     Kareem  Abdul-Jabbar          0
3          51   Mahmoud Abdul-Rauf    Mahmoud    Abdul-Rauf          0
4        1505    Tariq Abdul-Wahad      Tariq   Abdul-Wahad          0
...       ...                  ...        ...           ...        ...
4810  1627790           Ante Zizic       Ante         Zizic          0
4811    78647             Jim Zoet        Jim          Zoet          0
4812    78648            Bill Zopf       Bill          Zopf          0
4813  1627826          Ivica Zubac      Ivica         Zubac          1
4814    78650           Matt Zunic       Matt         Zunic          0

[4815 rows x 5 columns]

In [5]:
#EDA Questions= 1949 to 2020, top 5?
q1="""SELECT season,Count(Distinct team_id) as Count_teams
from draft_history
group by season
order by Count_teams desc limit 5"""
r1=pd.read_sql(q1,conn)
print(r1)

  season  Count_teams
0   2012           30
1   2011           30
2   2020           29
3   2015           29
4   2006           29

In [6]:
#top 10 teams
q2="""SELECT team_name, Count(distinct person_id) as total_drafted
FROM draft_history
GROUP BY team_name
order by total_drafted
Limit 10"""
r2=pd.read_sql(q2,conn)
print(r2)

      team_name  total_drafted
0       Huskies              5
1       Ironmen              7
2    Blackhawks             10
3          Jets             10
4       Packers             15
5       Zephyrs             15
6       Bobcats             20
7      Pelicans             22
8       Bombers             24
9  Steamrollers             24